scrummanager/src/br/com/scrummanager/web/controller/ConferenceController.java
package br.com.scrummanager.web.controller;

import java.util.List;

import javax.annotation.Resource;

import org.apache.commons.lang.StringUtils;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import br.com.scrummanager.model.Conference;
import br.com.scrummanager.model.Project;
import br.com.scrummanager.service.ConferenceService;

@Controller
@Scope("session")
public class ConferenceController {
	
	private Conference conference;
	@Resource
	private ConferenceService conferenceService;
	@Resource
	private ProjectController projectController;
	private Project selectedProject;
	private List<Conference> conferencesProject;
	
	
	public String newConference(){
		setSelectedProject(projectController.getProject());
		atualizarTela();
		return "conference";
	}

	public void atualizarTela() {
		conference = new Conference();
		conference.setProject(getSelectedProject());
		conferencesProject = conferenceService.procurarPorProjeto(getSelectedProject());
	}
	
	/**
	 * Salva registro
	 */
	public String gravar() {
		if (!conference.getIdentification().equals(StringUtils.EMPTY)) {
			conferenceService.gravar(getConference());
			MessagesController.msgConferenceSaved();
			atualizarTela();
		} else {
			MessagesController.msgFormIncorreto();
		}
		return "conference";
	}

	public void excluir() {
		conferenceService.excluir(getConference());
		atualizarTela();
	}
	
	public Project getSelectedProject() {
		return selectedProject;
	}
	
	public void setSelectedProject(Project selectedProject) {
		this.selectedProject = selectedProject;
	}
	
	public Conference getConference() {
		return conference;
	}
	
	public void setConference(Conference conference) {
		this.conference = conference;
	}
	
	public List<Conference> getConferencesProject() {
		return conferencesProject;
	}
}

scrummanager/src/br/com/scrummanager/web/controller/ImpedimentController.java
package br.com.scrummanager.web.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.faces.model.SelectItem;

import org.apache.commons.lang.StringUtils;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.com.scrummanager.model.Impediment;
import br.com.scrummanager.model.Project;
import br.com.scrummanager.model.Requirement;
import br.com.scrummanager.service.ImpedimentService;
import br.com.scrummanager.service.RequirementService;

@Controller
@Scope("session")
public class ImpedimentController {
	
	private Impediment impediment;
	private Requirement requirement;
	
	@Resource
	private ImpedimentService impedimentService;
	@Resource
	private ProjectController projectController;
	@Resource
	private RequirementController requirementController;
	private List<Impediment> impedimentsProject;
	private Project selectedProject;
	private Requirement selectedRequirement;
	private List<String> statusList;
	private List<SelectItem> requirementsProjectCombo;
	@Resource
	private RequirementService requirementService;
	private List<Requirement> requirementsProject;
	
	public String newImpediment(){
		setSelectedProject(projectController.getProject());
		refresh();
		return "impediment";
	}

	public void refresh() {
		impediment = new Impediment();
		impediment.setRequirement(new Requirement());
		impediment.setProject(getSelectedProject());
		impediment.setRegistrationDate(new Date());
		requirementsProject = requirementService.procurarPorProjeto(getSelectedProject());
		impedimentsProject = impedimentService.procurarPorProjeto(getSelectedProject());
	}
	
	/**
	 * Salva registro
	 */
	public String gravar() {
		
		if (StringUtils.isNotBlank(impediment.getIdentification())) {
			requirement = requirementService.findById(impediment.getRequirement().getId());
			impediment.setRequirement(requirement);
			impedimentService.gravar(getImpediment());
			MessagesController.msgImpedimentSaved();
			refresh();
		} else {
			MessagesController.msgFormIncorreto();
		}
		return "impediment";
	}
	
	/**
	 * Exclui um registro da tabela sprint
	 */
	public void excluir() {
		impedimentService.excluir(getImpediment());
		refresh();
	}
	
	public List<String> getStatusList(){
		if(statusList == null){
			statusList = new LinkedList<String>();
            statusList.add("Pendente");
            statusList.add("Resolvido");
            statusList.add("Postergado");

		}
		return statusList;
	}
	
	public List<SelectItem> getRequirements() {
		requirementsProjectCombo = new ArrayList<SelectItem>();
		if(getRequirementsProject() != null){
			for(Requirement requirement : getRequirementsProject()){
	        	requirementsProjectCombo.add(new SelectItem(requirement.getId(),requirement.getIdentification()));
	        }
		}
        return requirementsProjectCombo;
	}
	
	public Project getSelectedProject() {
		return selectedProject;
	}
	
	public void setSelectedProject(Project selectedProject) {
		this.selectedProject = selectedProject;
	}
	
	public Requirement getSelectedRequirement() {
		return selectedRequirement;
	}
	
	public void setSelectedRequirement(Requirement selectedRequirement) {
		this.selectedRequirement = selectedRequirement;
	}
	
	public Impediment getImpediment() {
		return impediment;
	}
	
	public void setImpediment(Impediment impediment) {
		this.impediment = impediment;
	}
	
	public List<Impediment> getImpedimentsProject() {
		return impedimentsProject;
	}
	
	public RequirementController getRequirementController() {
		return requirementController;
	}
	
	public List<Requirement> getRequirementsProject() {
		return requirementsProject;
	}
	
}

scrummanager/src/br/com/scrummanager/web/controller/KnowledgeController.java
package br.com.scrummanager.web.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;

import br.com.scrummanager.model.Knowledge;
import br.com.scrummanager.service.KnowledgeService;

@Controller
public class KnowledgeController {

	private Knowledge knowledge;

	private List<Knowledge> knowledgeList;

	@Resource
	KnowledgeService knowledgeService;

	public String newKnowledge() {
		refresh();
		return "knowledge";
	}

	public void refresh() {
		knowledge = new Knowledge();
		knowledgeList = new ArrayList<Knowledge>();
		knowledgeList = knowledgeService.listAll();
	}
	
	public void save(){
		knowledgeService.save(knowledge);
		refresh();
	}
	
	public void delete(){
		knowledgeService.delete(knowledge);
		refresh();
	}
	
	public Knowledge getKnowledge() {
		return knowledge;
	}

	public void setKnowledge(Knowledge knowledge) {
		this.knowledge = knowledge;
	}

	public List<Knowledge> getKnowledgeList() {
		return knowledgeList;
	}

	public void setKnowledgeList(List<Knowledge> knowledgeList) {
		this.knowledgeList = knowledgeList;
	}

}

scrummanager/src/br/com/scrummanager/web/controller/OcuppationController.java
package br.com.scrummanager.web.controller;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import org.springframework.stereotype.Controller;
import br.com.scrummanager.model.Ocuppation;
import br.com.scrummanager.service.OcuppationService;

@Controller
public class OcuppationController {
	
	private Ocuppation ocuppation;

	private List<Ocuppation> ocuppationList;

	@Resource
	OcuppationService ocuppationService;

	public String newOcuppation() {
		refresh();
		return "ocuppation";
	}

	public void refresh() {
		ocuppation = new Ocuppation();
		ocuppationList = new ArrayList<Ocuppation>();
		ocuppationList = ocuppationService.listAll();
	}
	
	public void save(){
		ocuppationService.save(ocuppation);
		refresh();
	}
	
	public void delete(){
		ocuppationService.delete(ocuppation);
		refresh();
	}
	
	public Ocuppation getOcuppation() {
		return ocuppation;
	}
	
	public void setOcuppation(Ocuppation ocuppation) {
		this.ocuppation = ocuppation;
	}

	public List<Ocuppation> getOcuppationList() {
		return ocuppationList;
	}
	
	public void setOcuppationList(List<Ocuppation> ocuppationList) {
		this.ocuppationList = ocuppationList;
	}

}

scrummanager/src/br/com/scrummanager/web/controller/PeopleController.java
package br.com.scrummanager.web.controller;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import org.springframework.stereotype.Controller;
import br.com.scrummanager.model.Skill;
import br.com.scrummanager.model.People;
import br.com.scrummanager.service.PeopleService;

@Controller
public class PeopleController {

	private People people;
	private List<People> listPeoples;
	private List<Skill> listAbilities;

	@Resource
	private PeopleService peopleService;

	public String newPeople() {
		atualizarTela();
		return "people";
	}
	
	public void atualizarTela() {
		people = new People();
		listAbilities = new ArrayList<Skill>();
		people.setAbilities(listAbilities);
		listPeoples = peopleService.listarTodos();
	}
	
	public void gravar(){
		peopleService.gravar(people);
		newPeople();
	}
	
	public void excluir(){
		peopleService.excluir(people);
		newPeople();
	}

	public People getPeople() {
		return people;
	}

	public void setPeople(People people) {
		this.people = people;
	}

	public List<People> getListPeoples() {
		return listPeoples;
	}

	public void setListPeoples(List<People> listPeoples) {
		this.listPeoples = listPeoples;
	}

	public List<Skill> getListAbilities() {
		return listAbilities;
	}

	public void setListAbilities(List<Skill> listAbilities) {
		this.listAbilities = listAbilities;
	}

	public PeopleService getPeopleService() {
		return peopleService;
	}

	public void setPeopleService(PeopleService peopleService) {
		this.peopleService = peopleService;
	}

}

scrummanager/src/br/com/scrummanager/web/controller/ProjectController.java
package br.com.scrummanager.web.controller;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import javax.faces.model.SelectItem;
import org.apache.commons.lang.StringUtils;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import br.com.scrummanager.model.People;
import br.com.scrummanager.model.Project;
import br.com.scrummanager.service.ProjectService;

@Controller
@Scope("session")
public class ProjectController {

	private Project project;

	private List<Project> listaProjetos;
	private List<SelectItem> peopleProjectCombo;
	private List<People> peopleProject;

	@Resource
	private ProjectService projectService;
	

//	private List<SelectItem> comboProjetos;

	public String newProject(){
		atualizarTela();
		return "project";
	}

	public String painelUsuario(){
		atualizarTela();
		return "painelUsuario.xhtml";
	}

	public void atualizarTela() {
		project = new Project();
		listaProjetos = new ArrayList<Project>();
		listaProjetos = projectService.listarTodos();
	}

	/**
	 * Salva registro
	 */
	public String gravar() {
		System.out.println("Entrou no gravar!");
		if (!project.getIdentification().equals(StringUtils.EMPTY)) {
			projectService.gravar(getProject());
			MessagesController.msgProjetoCadastrado();
			atualizarTela();
		} else {
			MessagesController.msgFormIncorreto();
		}
		return "project";
	}

	/**
	 * Exclui um registro da tabela project
	 */
	public void excluir() {
		projectService.excluir(getProject());
		atualizarTela();
	}

	public List<SelectItem> getPeoples() {
		peopleProjectCombo = new ArrayList<SelectItem>();
		if(getPeopleProject() != null){
			for(People people : getPeopleProject()){
				peopleProjectCombo.add(new SelectItem(people.getId(),people.getName()));
	        }
		}
        return peopleProjectCombo;
	}

	public String entrar() {
		return "projectMenu";
	}

	public Project getProject() {
		return project;
	}

	public List<Project> getListaProjetos() {
		return listaProjetos;
	}

	public void setProject(Project project) {
		this.project = project;
	}
	
	public List<People> getPeopleProject() {
		return peopleProject;
	}
	
	
}

scrummanager/src/br/com/scrummanager/web/controller/RequirementController.java
package br.com.scrummanager.web.controller;

import java.util.LinkedList;
import java.util.List;
import javax.annotation.Resource;
import org.apache.commons.lang.StringUtils;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import br.com.scrummanager.model.Project;
import br.com.scrummanager.model.Requirement;
import br.com.scrummanager.service.RequirementService;

@Controller
@Scope("session")
public class RequirementController {
	
	private Requirement requirement;
	
	@Resource
	private RequirementService requirementService;
	@Resource
	private ProjectController projectController;
	private List<Requirement> requirementsProject;
	
	private Project selectedProject;
	private List<String> statusList;
	
	public String newRequirement(){
		setSelectedProject(projectController.getProject());
		atualizarTela();
		return "requirement";
	}

	public void atualizarTela() {
		requirement = new Requirement();
		requirement.setProject(getSelectedProject());
		requirementsProject = requirementService.procurarPorProjeto(getSelectedProject());
	}
	
	/**
	 * Salva registro
	 */
	public String gravar() {
		if (!requirement.getIdentification().equals(StringUtils.EMPTY)) {
			requirementService.gravar(getRequirement());
			MessagesController.msgRequirementSaved();
			atualizarTela();
		} else {
			MessagesController.msgFormIncorreto();
		}
		return "requirement";
	}


	/**
	 * Exclui um registro da tabela sprint
	 */
	public void excluir() {
		requirementService.excluir(getRequirement());
		atualizarTela();
	}
	
	public Project getSelectedProject() {
		return selectedProject;
	}
	
	public void setSelectedProject(Project selectedProject) {
		this.selectedProject = selectedProject;
	}
	
	public Requirement getRequirement() {
		return requirement;
	}
	
	public void setRequirement(Requirement requirement) {
		this.requirement = requirement;
	}
	
	public List<Requirement> getRequirementsProject() {
		return requirementsProject;
	}
	
	public List<String> getStatusList(){
		if(statusList == null){
			statusList = new LinkedList<String>();
            statusList.add("Pendente");
            statusList.add("Executando");
            statusList.add("Feito");

		}
		return statusList;
	}
}

scrummanager/src/br/com/scrummanager/web/controller/TaskController.java
package br.com.scrummanager.web.controller;

import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import javax.annotation.Resource;
import org.apache.commons.lang.StringUtils;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import br.com.scrummanager.model.Sprint;
import br.com.scrummanager.model.Task;
import br.com.scrummanager.service.TaskService;

@Controller
@Scope("session")
public class TaskController implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Task task;
	private List<Task> listaTarefasDeUmaSprint;
	private Sprint selectedSprint;
	private List<String> statusList;
	private List<String> statusTestList;
	@Resource
	private TaskService taskService;
	@Resource
	private SprintController sprintController;


	public String newTask(){
		setSelectedSprint(sprintController.getSprint());
		atualizarTela();
		return "task";
	}
	
	public void atualizarTela() {
		task = new Task();
		task.setSprint(getSelectedSprint());
		listaTarefasDeUmaSprint = taskService.procurarPorSprint(getSelectedSprint());
	}
	
	public String gravar(){
		if(!task.getIdentification().equals(StringUtils.EMPTY)){
			taskService.gravar(getTask());
			MessagesController.msgTarefaCadastrada();
			atualizarTela();
		}else{
			MessagesController.msgFormIncorreto();
		}
		return "task";
	}
	
	/**
	 * Exclui um registro da tabela sprint
	 */
	public void excluir() {
		taskService.excluir(getTask());
		atualizarTela();
	}
	
	//cadastrar na tabela e fazer um List<SeletcItem>?
	public List<String> getStatusList(){
		if(statusList == null){
			statusList = new LinkedList<String>();
            statusList.add("Pendente");
            statusList.add("Executando");
            statusList.add("Feita");

		}
		return statusList;
	}
	
	public List<String> getStatusTestList(){
		if(statusTestList == null){
			statusTestList = new LinkedList<String>();
			statusTestList.add("Testada");
			statusTestList.add("Pendente");
		}
		return statusTestList;
	}

	public Task getTask() {
		return task;
	}
	
	public void setTask(Task task) {
		this.task = task;
	}
	
	public List<Task> getListaTarefasDeUmaSprint() {
		return listaTarefasDeUmaSprint;
	}
	
	public void setListaTarefasDeUmaSprint(List<Task> listaTarefasDeUmaSprint) {
		this.listaTarefasDeUmaSprint = listaTarefasDeUmaSprint;
	}
	
	public Sprint getSelectedSprint() {
		return selectedSprint;
	}
	
	public void setSelectedSprint(Sprint selectedSprint) {
		this.selectedSprint = selectedSprint;
	}
}

scrummanager/WebContent/paginas/usuario/impediment.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.prime.com.tr/ui">


<ui:composition template="templates/tUsuario.xhtml">

	<ui:define name="titulo">
    	Scrum Manager - Impedimentos
    </ui:define>

	<ui:define name="conteudo">

		<style type="text/css">
.ui-dashboard-column {
	width: 275px;
}
</style>

		<f:view>
			<h:form id="impedimentForm">

				<br />
				<h2>
					<h:outputText value="#{projectController.project.identification}" />
				</h2>
				<br />
				<p:growl id="msgs" />

				<!-- Lista de Impedimentos -->
				<p:panel id="painelList" header="Impedimentos do Projeto"
					style="text-align:left; width:100%;" toggleable="true"
					collapsed="false">

					<p:dataTable value="#{impedimentController.impedimentsProject}"
						id="tabela" emptyMessage="Nenhum registro encontrado"
						rowIndexVar="var" paginator="true" paginatorPosition="bottom"
						firstPageLinkLabel="Primeira" previousPageLinkLabel="Anterior"
						nextPageLinkLabel="Proxima" lastPageLinkLabel="ultima" rows="5"
						var="impediment">

						<p:column>
							<f:facet name="header">
								<h:outputText value="Data" />
							</f:facet>
							<h:outputText value="#{impediment.registrationDate}">
								<f:convertDateTime pattern="dd/MM/yyyy"></f:convertDateTime>
							</h:outputText>
						</p:column>

						<p:column>
							<f:facet name="header">
								<h:outputText value="Identificador" />
							</f:facet>
							<h:outputText value="#{impediment.identification}">
								<f:convertDateTime pattern="dd/MM/yyyy"></f:convertDateTime>
							</h:outputText>
						</p:column>

						<p:column>
							<f:facet name="header">
								<h:outputText value="Descrição" />
							</f:facet>
							<h:outputText value="#{impediment.description}" ajax="false" />
						</p:column>

						<p:column>
							<f:facet name="header">
								<h:outputText value="Requisito associado" />
							</f:facet>
							<h:outputText value="#{impediment.requirement.description}" />
						</p:column>

						<p:column>
							<f:facet name="header">
								<h:outputText value="Status" />
							</f:facet>
							<h:outputText value="#{impediment.status}" />
						</p:column>

						<p:column>
							<f:facet name="header">
								<h:outputText value="Motivo de postergação" />
							</f:facet>
							<h:outputText value="#{impediment.reason}" />
						</p:column>

						<p:column style="text-align: center;">
							<p:commandButton image="ui-icon-pencil" ajax="false"
								value="alterar" update="impedimentForm, msgs"
								actionListener="#{impedimentController.refresh}">
								<f:setPropertyActionListener
									target="#{impedimentController.impediment}"
									value="#{impediment}" />
							</p:commandButton>
						</p:column>

						<p:column style="text-align: center;">
							<p:commandButton image="ui-icon-closethick" ajax="false"
								action="#{impedimentController.excluir}" value="excluir"
								update="impedimentForm, msgs"
								actionListener="#{messagesController.msgExclusao}">
								<f:setPropertyActionListener
									target="#{impedimentController.impediment}"
									value="#{impediment}" />
							</p:commandButton>
						</p:column>
					</p:dataTable>
				</p:panel>
				<br />
				<p:panel id="painelCadastro" header="Cadastrar Novo Impedimento">
					<h:panelGrid columns="3">

						<h:outputLabel value="Idenficador">
							<h:outputLabel value="*" style="color:green;" />
						</h:outputLabel>
						<p:inputText id="identification"
							value="#{impedimentController.impediment.identification}"
							size="15" />
						<p:commandButton tabindex="99" image="ui-icon-help"
							title="Descrição do Requisito" style="width: 1em; height: 1em;" />

						<h:outputLabel value="Requisito:">
						</h:outputLabel>
						<h:selectOneMenu
							value="#{impedimentController.impediment.requirement.id}">
							<f:selectItems value="#{impedimentController.requirements}" />
						</h:selectOneMenu>
						<p:commandButton tabindex="99" image="ui-icon-help"
							title="Requisito associado ao impedimento"
							style="width: 1em; height: 1em;" />

						<h:outputLabel value="Descrição:">
							<h:outputLabel value="*" style="color:green;" />
						</h:outputLabel>
						<p:inputText id="description"
							value="#{impedimentController.impediment.description}" size="45" />
						<p:commandButton tabindex="99" image="ui-icon-help"
							title="Descrição do Requisito" style="width: 1em; height: 1em;" />

						<h:outputLabel value="Status:">
							<h:outputLabel value="*" style="color:green;" />
						</h:outputLabel>
						<h:selectOneMenu value="#{impedimentController.impediment.status}">
							<f:selectItems value="#{impedimentController.statusList}" />
						</h:selectOneMenu>
						<p:commandButton tabindex="99" image="ui-icon-help"
							title="Status do impedimento" style="width: 1em; height: 1em;" />

						<h:outputLabel value="Motivo da postergação:">
						</h:outputLabel>
						<p:inputText id="reason"
							value="#{impedimentController.impediment.reason}" size="45" />
						<p:commandButton tabindex="99" image="ui-icon-help"
							title="Motivo do impedimento ter sido postergado"
							style="width: 1em; height: 1em;" />

					</h:panelGrid>
					<br />
					<p:commandButton image="ui-icon-circle-plus" value="Gravar"
						action="#{impedimentController.gravar}" ajax="false"
						update="painelCadastro, painelList, msgs">
						<f:setPropertyActionListener
							target="#{impedimentController.impediment.project}"
							value="#{projectController.project}" />
					</p:commandButton>
				</p:panel>
				<br/>
				<p:commandButton value="Voltar" action="projectMenu" 
						ajax="false" />

			</h:form>
		</f:view>
	</ui:define>
</ui:composition>
</html>

scrummanager/WebContent/paginas/usuario/knowledge.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.prime.com.tr/ui">


<ui:composition template="templates/tUsuario.xhtml">

	<ui:define name="titulo">
    	Scrum Manager - Tecnologias e Conhecimentos na área de atuação
    </ui:define>

	<ui:define name="conteudo">

		<style type="text/css">
.ui-dashboard-column {
	width: 275px;
}
</style>

		<f:view>
			<h:form id="knoledgeForm">
			<p:tooltip global="true" />

				<p:growl id="msgs" />

				<!-- Lista de knoledge) -->
				<p:panel id="painelList" header="Conhecimentos"
					style="text-align:left; width:100%;" toggleable="true"
					collapsed="false">


					<p:dataTable value="#{knowledgeController.knowledgeList}"
						id="tabela" emptyMessage="Nenhum registro encontrado"
						rowIndexVar="var" paginator="true" paginatorPosition="bottom"
						firstPageLinkLabel="Primeira" previousPageLinkLabel="Anterior"
						nextPageLinkLabel="Proxima" lastPageLinkLabel="ultima" rows="5"
						var="knowledge">

						<p:column>
							<f:facet name="header">
								<h:outputText value="Conhecimento" />
							</f:facet>
							<h:outputText value="#{knowledge.name}" />
						</p:column>

						<p:column style="text-align: center;">
							<p:commandButton image="ui-icon-pencil" ajax="false"
								value="alterar" update="knoledgeForm, msgs"
								actionListener="#{knowledgeController.refresh}" >
								<f:setPropertyActionListener
									target="#{knowledgeController.knowledge}"
									value="#{knowledge}" />
							</p:commandButton>
						</p:column>

						<p:column style="text-align: center;">
							<p:commandButton image="ui-icon-closethick" ajax="false"
								action="#{knowledgeController.delete}" value="excluir"
								update="knoledgeForm, msgs"
								actionListener="#{messagesController.msgExclusao}">
								<f:setPropertyActionListener
									target="#{knowledgeController.knowledge}"
									value="#{knowledge}" />
							</p:commandButton>
						</p:column>

					</p:dataTable>
				</p:panel>
				<br />
				<p:panel id="painelCadastro" header="Cadastrar Novo Conhecimento">

					<h:panelGrid columns="3">
					
						<h:outputLabel value="Conhecimento">
							<h:outputLabel value="*" style="color:green;" />
						</h:outputLabel>
						<p:inputText id="knowledge"
							value="#{knowledgeController.knowledge.name}"
							size="45" />
						<p:commandButton tabindex="99" image="ui-icon-help"
							title="Nome do Conhecimento" style="width: 1em; height: 1em;" />
					</h:panelGrid>
					<br />
					<p:commandButton image="ui-icon-circle-plus" value="Gravar"
						action="#{knowledgeController.save}" ajax="false"
						update="painelList, painelCadastro, msgs">
					</p:commandButton>
				</p:panel>
				<br/>
				<p:commandButton value="Voltar" action="rhMenu" 
						ajax="false" />
			</h:form>
		</f:view>
	</ui:define>
</ui:composition>
</html>

scrummanager/WebContent/paginas/usuario/painelUsuario.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.prime.com.tr/ui">


<ui:composition template="/paginas/usuario/templates/tUsuario.xhtml">

	<ui:define name="titulo">
    	Scrum Manager - Gerenciamento de Projetos
    </ui:define>

	<ui:define name="conteudo">

		<h:form>
			<p:growl id="growl" showDetail="true" />
			<br />
			<h:panelGrid columns="2" width="100%">
				<p:panel style="width:98%; text-align: center; border: 0;" >
					<p:graphicImage id="image" value="/img/projeto.gif"
						style="width: 10em; height: 10em;" /><br/>
					<p:commandButton value="Gestão de Projetos"
						action="#{projectController.newProject}" ajax="false" style="width: 12em; height: 3em;"/>


				</p:panel>
				<p:panel style="width:98%; text-align: center; border: 0;">
					<p:graphicImage id="imagePessoas" value="/img/pessoas2.gif"
						style="width: 10em; height: 10em;" /><br/>
					<p:commandButton value="Gestão de Pessoas" action="rhMenu" style="width: 12em; height: 3em;"
						ajax="false" />
				</p:panel>
			</h:panelGrid>
			<br />
			<br />
			<br />


		</h:form>
	</ui:define>
</ui:composition>
</html>